package com.app.devigetoscarolivares.Models

data class RedditEntry(
var domain:String?,
var banned_by:String?,
var media_embed:String?,// {},
var subreddit:String?,
var selftext_html:String?,
var selftext:String?,
var likes:String?, //null,
var user_reports:String?,// [],
var secure_media:String?,
var link_flair_text:String?,
var id:String?,
var gilded:Int?,
var secure_media_embed:String?,
var clicked:Boolean?,
var report_reasons:String?,
var author:String?,
var media:String?,
var score:String?,
var approved_by:String?,
var over_18:Boolean?,
var hidden:Boolean?,
var thumbnail:String?,
var subreddit_id:String?,
var edited:Boolean?,
var link_flair_css_class:String?,
var author_flair_css_class:String?,
var downs:Int?,
var mod_reports:String?,
var saved:Boolean?,
var is_self:Boolean?,
var name:String?,
var permalink:String?,
var stickied:Boolean?,
var created:Int?,
var url:String?,
var author_flair_text:String?,
var title:String?,
var created_utc:Int?,
var ups:Int?,
var num_comments:Int?,
var visited:Boolean?,
var num_reports:Int?,
var distinguished:String?
)
